#!/usr/bin/env bash

## Commands Executed By Openbox Powermenu

## Rofi #############################################
DIR="$HOME/.config/polybar/rofi/themes"
MSG="Options  -  yes / y / no / n"
current_desktop=$(wmctrl -m |sed -n 1p | sed -e 's/Name: //g') 

cdialog () {
rofi -dmenu\
    -i\
    -no-fixed-num-lines\
    -p "Are You Sure? : "\
    -theme "$DIR"/confirm.rasi
}

## Options #############################################
if  [[ $1 = "--logout" ]]; then
	ans=$(cdialog)
	if [[ $ans == "yes" ]] || [[ $ans == "YES" ]] || [[ $ans == "y" ]]; then
        if [[ $current_desktop == "Openbox" ]]; then
			openbox --exit
		elif [[ $current_desktop == "i3" ]]; then
			i3 exit
		elif [[ $current_desktop == "bspwm" ]]; then
			bspc quit
		fi
	elif [[ $ans == "no" ]] || [[ $ans == "NO" ]] || [[ $ans == "n" ]]; then
        exit
    else
        rofi -theme "$DIR"/askpass.rasi -e "$MSG"
    fi

elif  [[ $1 = "--suspend" ]]; then
	ans=$(cdialog)
	if [[ $ans == "yes" ]] || [[ $ans == "YES" ]] || [[ $ans == "y" ]]; then
		mpc -q pause
		playerctl -a stop
		amixer set Master mute
		betterlockscreen --suspend
	elif [[ $ans == "no" ]] || [[ $ans == "NO" ]] || [[ $ans == "n" ]]; then
		exit
    else
		rofi -theme "$DIR"/askpass.rasi -e "$MSG"
    fi

elif  [[ $1 = "--reboot" ]]; then
	ans=$(cdialog)
	if [[ $ans == "yes" ]] || [[ $ans == "YES" ]] || [[ $ans == "y" ]]; then
        systemctl reboot
	elif [[ $ans == "no" ]] || [[ $ans == "NO" ]] || [[ $ans == "n" ]]; then
        exit
    else
        rofi -theme "$DIR"/askpass.rasi -e "$MSG"
    fi

elif  [[ $1 = "--shutdown" ]]; then
	ans=$(cdialog)
	if [[ $ans == "yes" ]] || [[ $ans == "YES" ]] || [[ $ans == "y" ]]; then
        systemctl poweroff
	elif [[ $ans == "no" ]] || [[ $ans == "NO" ]] || [[ $ans == "n" ]]; then
        exit
    else
        rofi -theme "$DIR"/askpass.rasi -e "$MSG"
    fi

## Help Menu #############################################
else
echo "
Powermenu For Openbox Menu

Available options:
--logout	--suspend	--reboot	--shutdown
"
fi
