#!/bin/bash

run(){
	if command -v $1 &> /dev/null; then 
		if [[ 'pidof $1' ]]; then
		killall -9 $1
		fi
		$1 $2 $3 &
		exit &
	else 
		echo "$1 is not installed" > log.txt
	fi
}


check(){
	programs=(dunst picom dunst copyq xfsettingsd polybar discord kdeconnect-indicator trackma-gtk)
	for program in "${programs[@]}"; do
		run $program 
	done

}

run mpd 

run /usr/lib/xfce-polkit/xfce-polkit

run dunst

## xfce4-settings daemon
run xfsettingsd 

# Enable power management
run xfce4-power-manager 

### Thunar Daemon
run thunar --daemon

## Restore Wallpaper
#run wal -Re 

## Start mpd

run mpd-mpris 

## CopyQ
run copyq --start-server 

## Touchegg
run touchegg --daemon &
#exec touchegg &

## Discord Launch
run discord &

## KDE Conenct
run kdeconnect-indicator &


