#!/bin/bash

# Color files
ALFILE="$HOME/.config/alacritty/colors.yml"
PFILE="$HOME/.config/polybar/colors.ini"
RFILE="$HOME/.config/polybar/rofi/themes/colors.rasi"
DFILE="$HOME/.config/BetterDiscord/data/stable/custom.css"
NFILE="$HOME/.config/dunst/dunstrc"
GFILE="$HOME/.config/geany/colorschemes/darcula.conf"
ZFILE="$HOME/.config/zathura/zathurarc"
GZFILE="$HOME/.config/zathura/genzathurarc"
ASFILE="$HOME/.cache/wal/colors-rofi-dark.rasi"
AFILE="$HOME/.config/aniwrapper/themes/aniwrapper.rasi"

## Change colors
change_colors() {
	
	# polybar	
	cat > $PFILE <<- EOF
		[color]
		;; main colors
		background = ${BG}
		systemtray = ${ST}
		foreground = $FG
		primary = $FG
		red = $red
		green = $green
		yellow = $yellow
		blue = $blue
		magenta = $magenta
		cyan = $cyan
		white = $white
		
		EOF
		
	# rofi
	cat > $RFILE <<- EOF
	/* colors */
	* {
		background:       ${BG}FF; 
		background-alt:   ${BG}FF;
		foreground:       ${FG}FF;
		selected:         ${blue}FF;
		highlight:        ${FG}FF;
		urgent:           ${blue}FF;
		on:               ${red}FF;
		off:              ${red}FF;
	}
		EOF
	
	# alacritty 
	cat > $ALFILE <<- EOF 
	#Colors 
	colors:
	  primary:
	    background: '$BG'
	    foreground: '$FG'
	  cursor:
	    text:       '$black'
	    cursor:     '$white'
	  normal:
	    black:      '$black'
	    red:        '$red'
	    green:      '$green'
	    yellow:     '$yellow'
	    blue:       '$blue'
	    magenta:    '$magenta'
	    cyan:       '$cyan'
	    white:      '$white'
	  bright:
	    black:      '$bright_black'
	    red:        '$bright_red'
	    green:      '$bright_green'
	    yellow:     '$bright_yellow'
	    blue:       '$bright_blue'
	    magenta:    '$bright_magenta'
	    cyan:       '$bright_cyan'
	    white:      '$bright_white'
	EOF
	
	# discord
	if [[ -f $DFILE ]]; then 
	sed -i -e "s/--accent-color: #.*/--accent-color: ${FG};/g" $DFILE
	sed -i -e "s/--settings-icon-color: #.*/--settings-icon-color: ${FG};/g" $DFILE
	sed -i -e "s/--background-1: #.*/--background-1: ${BG};/g" $DFILE
	sed -i -e "s/--background-2: #.*/--background-2: ${BG};/g" $DFILE
	sed -i -e "s/--background-accent: #.*/--background-accent: ${BG};/g" $DFILE
	sed -i -e "s/--button-background-hover: #.*/--button-background-hover: ${red};/g" $DFILE
	sed -i -e "s/--tab-selected: #.*/--tab-selected: ${blue};/g" $DFILE
	sed -i -e "s/--text-muted: #.*/--text-muted: ${FG};/g" $DFILE
	fi 
	
	# dunst
	sed -i -e "s/background = \"#.*\"/background = \"${BG}\"/g" $NFILE
	sed -i -e "s/foreground = \"#.*\"/foreground = \"${FG}\"/g" $NFILE
	sed -i -e "s/highlight = \"#.*\"/highlight = \"${FG}\"/g" $NFILE
	sed -i -e "s/frame_color = \"#.*\"/frame_color = \"${yellow}\"/g" $NFILE

	# zathura
	$GZFILE > $ZFILE
		
	# aniwrapper 
	cat $ASFILE > $AFILE
	
	# spotify
	# Spotify can be themed using the xrdb backend i.e. ${xrdb:color0:#222}
	
	# geany
	sed -i -e "s/bg=#.*/bg=${BG}/g" $GFILE
	sed -i -e "s/fg=#.*/fg=${FG}/g" $GFILE
	sed -i -e "s/margin_bg_grey=#.*/margin_bg_grey=${black}/g" $GFILE
	

	
}

## Check if all the required apps are installed and install the missing ones
apps=(betterlockscreen wal-telegram spicetify pywalfox openbox\
	 aniwrapper polybar rofi zathura geany alacritty dunst betterdiscordctl)

checkApps(){
	for _apps in "${apps[@]}"; do
		let i++
		if ! command -v $_apps &> /dev/null; then
			apps1+=("$_apps ")			
		else 
			if [[ $i = "${#apps[@]}" ]]; then 
				main
				break		
			fi
		fi
	done
	
	if [[ "${#apps1[@]}" > 0 ]]; then
		yay -S ${apps1[@]} && checkApps
		exit 0
	fi
	}

## Change the wallpaper for both sddm and grub 
# this function only works with the themes included in the install script 
lockWal(){
	## remove the background file for sddm and replace it with a hard link of the wallpaper 
	sudo rm /usr/share/sddm/themes/arch/components/artwork/background.jpg && \
	sudo ln ~/.config/wpg/wallpapers/wallpaper.jpg \
	/usr/share/sddm/themes/arch/components/artwork/background.jpg
	## remove the background file for grub and replace it with a symbolic  link of the wallpaper 
	sudo rm /usr/share/grub/themes/Arch/background.jpg && \
	sudo ln -s ~/.config/wpg/wallpapers/wallpaper.jpg \
	/usr/share/grub/themes/Arch/background.jpg
	}

## Send a signal to phone to change wallpaper (requires automate to be set up)
phoneWal(){
	if command -v kdeconnect-cli &> /dev/null; then 
		deviceID=$(kdeconnect-cli -a --id-only)  
		kdeconnect-cli -d $deviceID --share \
		$HOME/.config/wpg/wallpapers/wallpaper.jpg && kdeconnect-cli -d $deviceID --ping 
		exit 0
	else 
		echo "kde connect is not installed"
	fi
	}

## Kill already running process
kill(){
	_ps=(dunst)
	for _prs in "${_ps[@]}"; do
		if [[ `pidof ${_prs}` ]]; then
			killall -9 ${_prs} 
			${_prs} 
		fi
	done
	}
	
## Check if the command exists and then runs it
check(){
	if command -v $1 &> /dev/null; then 
		$1 $2 $3
	#else 
		#echo " $1 is not installed"
	fi
	}
	
wpgConfig(){
	sed -i -e 's/execute_cmd = false/execute_cmd = true/g' ~/.config/wpg/wpg.conf
	sed -i -e 's/auto_adjust = false/auto_adjust = true/g' ~/.config/wpg/wpg.conf
	sed -i -e "s/command = .*/command = \/home\/$(whoami)\/.scripts\/wpgtk main/g" ~/.config/wpg/wpg.conf
	}	
	
pick(){
	wal=$(sxiv -t -o -r -b -g $(echo 900x700+$xl+$yl) ~/Pictures/Wallpapers | xargs)
	fixed=$(echo "$wal" | sed 's/ /\\ /g')
	echo $fixed
	wpg -s $fixed
	}	
	
main(){
	change_colors 
	sh ~/.config/polybar/launch.sh 
	kill &
	check razer-cli -a &
	check pywalfox update 
	check openbox --reconfigure 
	check wal-telegram --wal 
	check spicetify update 
	phoneWal
	check betterlockscreen -u $wallpaper
	}

## Check if wpg is installed and get colors
if [[ -f "/usr/bin/wpg" ]]; then
	
	## Import colors from wal
	. "$HOME/.cache/wal/colors.sh"

	# Normal colors
	BG=`printf "%s\n" "$background"`
	ST=`printf "%s\n" "$background"`
	FG=`printf "%s\n" "$foreground"`
	FGA=`printf "%s\n" "$foreground"`
	black=`printf "%s\n" "$color0"`
	red=`printf "%s\n" "$color1"`
	green=`printf "%s\n" "$color2"`
	yellow=`printf "%s\n" "$color3"`
	blue=`printf "%s\n" "$color4"`
	magenta=`printf "%s\n" "$color5"`
	cyan=`printf "%s\n" "$color6"`
	white=`printf "%s\n" "$color7"`
	# Bright colors
	bright_black=`printf "%s\n" "$color8"`
	bright_red=`printf "%s\n" "$color9"`
	bright_green=`printf "%s\n" "$color10"`
	bright_yellow=`printf "%s\n" "$color11"`
	bright_blue=`printf "%s\n" "$color12"`
	bright_magenta=`printf "%s\n" "$color13"`
	bright_cyan=`printf "%s\n" "$color14"`
	bright_white=`printf "%s\n" "$color15"`
	if [ "$(echo $(file --extension $wallpaper | sed -e 's/.*://'))" = "png" ]; then
		cp $wallpaper ~/.config/wpg/wallpapers/ && 
		mogrify -format jpg ~/.config/wpg/wallpapers/*.png &&
		rm ~/.config/wpg/wallpapers/$(echo "$wallpaper" | cut -f6 -d "/") &&
		mv ~/.config/wpg/wallpapers/$(echo "$wallpaper" | cut -f6 -d "/" | cut -f1 -d ".").jpg ~/.config/wpg/wallpapers/wallpaper.jpg 
		echo "file was png" 
	else	
		cp $wallpaper ~/.config/wpg/wallpapers/wallpaper.jpg
	fi
	xrdb -merge ~/.cache/wal/colors.Xresources
	
else
	echo "[!] 'wpgtk' is not installed."
	echo "Installing from the AUR..." 
	yay -S wpgtk-git
	wpgConfig
	wpg-install.sh -r -g -o
fi

"$@"
