#!/usr/bin/env bash

# Kill already running process
#killall -9 picom dunst ksuperkey mpd xfce-polkit xfce4-power-manager polybar trackma-gtk xfsettingsd

_ps=(picom dunst ksuperkey mpd xfce-polkit xfce4-power-manager polybar trackma-gtk xfsettingsd touchegg)
for _prs in "${_ps[@]}"; do
	if [[ `pidof ${_prs}` ]]; then
		killall -9 ${_prs}
	fi
done

## Restore Wallpaper
#nitrogen --restore &

## xfce4-settings daemon
xfsettingsd &

## polkit agent
#if [[ ! `pidof xfce-polkit` ]]; then
	#/usr/lib/xfce-polkit/xfce-polkit &
#fi

## Restore Wallpaper
#exec wal -Re &
feh --no-fehbg --bg-fill $HOME/.config/wpg/wallpapers/wallpaper.jpg &

## Enable power management
xfce4-power-manager &

## Start Compositing Manager
exec picom &

## Notification Daemon
exec dunst &

## Start Music Player Daemon
exec mpd &

## Launch Plank
# exec plank &

## Thunar Daemon
#exec thunar --daemon &

## Launch Polybar
bash ~/.config/polybar/launch.sh &

## Discord Launch
exec discord &

## KDE Conenct
exec kdeconnect-indicator &

#CopyQ
exec copyq &

## Excute Screenshot script
bash ~/.scripts/check.sh &

## Trackma Launch
exec trackma-gtk &

## Touchegg
exec touchegg --daemon &
exec touchegg &

## Enable Super Keys For Menu
ksuperkey -e 'Super_L=Alt_L|F1' &
ksuperkey -e 'Super_R=Alt_L|F1' &

