#!/usr/bin/env bash

## Copyright (C) 2020-2021 Aditya Shakya <adi1090x@gmail.com>
## Everyone is permitted to copy and distribute copies of this file under GNU-GPL3

## Kill if already running
killall -9 nitrogen xfsettingsd picom polybar mpd dunst ksuperkey xfce4-power-manager mpd-mpris

## Restore Wallpaper
#nitrogen --restore &

## xfce4-settings daemon
xfsettingsd &

## polkit agent
#if [[ ! `pidof xfce-polkit` ]]; then
	#/usr/lib/xfce-polkit/xfce-polkit &
#fi

## Enable power management
xfce4-power-manager &

## Launch Polybar
bash ~/.config/polybar/launch.sh &

## Start Compositing Manager
exec picom &

## Notification Daemon
exec dunst &

## Restore Wallpaper
exec wal -R &

## Start Music Player Daemon
exec mpd &

## Launch Plank
# exec plank &

## Thunar Daemon
exec thunar --daemon &

## Discord Launch
exec discord &

## KDE Conenct
exec kdeconnect-indicator &

#CopyQ
exec copyq &

## Excute Screenshot script
bash /home/tarek/.scripts/sc.sh &

## Touchegg
exec touchegg --daemon &
exec touchegg &

## Enable Super Keys For Menu
ksuperkey -e 'Super_L=Alt_L|F1' &
ksuperkey -e 'Super_R=Alt_L|F1' &

